# Generated by Django 4.2.5 on 2023-09-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_product_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='price',
        ),
    ]
